// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

import 'package:firebase_core/firebase_core.dart';
import 'firebase_options.dart';

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDoet_0EQtJJml6TKLKaW8-SoKONp5DCJ4',
    appId: '1:536865609365:web:1737f761203c7653e1ed9c',
    messagingSenderId: '536865609365',
    projectId: 'bookswapapp-cd75d',
    authDomain: 'bookswapapp-cd75d.firebaseapp.com',
    storageBucket: 'bookswapapp-cd75d.firebasestorage.app',
    measurementId: 'G-BYJW9RPQMP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQ5J3CgZpU-WMllth1dgEPiPGO-kJZ4H4',
    appId: '1:536865609365:android:77b9eb27de0250abe1ed9c',
    messagingSenderId: '536865609365',
    projectId: 'bookswapapp-cd75d',
    storageBucket: 'bookswapapp-cd75d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDuGbxC_s3O2wBS-aD-jgEsogeNeO0v6RI',
    appId: '1:536865609365:ios:6ab4f85d0324622be1ed9c',
    messagingSenderId: '536865609365',
    projectId: 'bookswapapp-cd75d',
    storageBucket: 'bookswapapp-cd75d.firebasestorage.app',
    iosBundleId: 'com.example.bookswapApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDuGbxC_s3O2wBS-aD-jgEsogeNeO0v6RI',
    appId: '1:536865609365:ios:6ab4f85d0324622be1ed9c',
    messagingSenderId: '536865609365',
    projectId: 'bookswapapp-cd75d',
    storageBucket: 'bookswapapp-cd75d.firebasestorage.app',
    iosBundleId: 'com.example.bookswapApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDoet_0EQtJJml6TKLKaW8-SoKONp5DCJ4',
    appId: '1:536865609365:web:89cecf4c83677619e1ed9c',
    messagingSenderId: '536865609365',
    projectId: 'bookswapapp-cd75d',
    authDomain: 'bookswapapp-cd75d.firebaseapp.com',
    storageBucket: 'bookswapapp-cd75d.firebasestorage.app',
    measurementId: 'G-3R1XE1BNVF',
  );
}
